config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "recipes#index"
  get "/recipes", to: "recipes#index"
  get "/about", to: "pages#about"
  get "/contact", to: "pages#contact"
  get "/recipes/:id", to: "recipes#show", as: "recipe"
  get "/favourites", to: "favourites#index"
  get "/ratings", to: "ratings#index"
  get "/account", to: "accounts#show"
  get "/category/:title", to: "categories#show", as: "category_show"
  get "/favourites/create", to: "favourites#create"

  post "/favourites/create", to: "favourites#create"
  post "/ratings/create", to: "ratings#create"
  delete '/favourites/:id', to: 'favourites#destroy', as: :favourite

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :recipe
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :user
  belongs_to :recipe

  validates_uniqueness_of :recipe_id, scope: :user_id
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :recipe
  belongs_to :user

  validates :value, presence: true, inclusion: { in: 1..5 }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :category
  has_many :favourites
  has_many :ratings

  include PgSearch::Model
  pg_search_scope :search_by_recipe,
                  against: [ :title ],
                  associated_against: {
                  category:[ :title ]
                  },
                  using: {
                    tsearch: { prefix: true }
                  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :favourites
  has_many :ratings
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def show
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find_by(title: params[:title].capitalize)
    @recipes = Recipe.where(category_id: @category.id)
  end
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  before_action :authenticate_user!

  def index
    @favourite_recipes = current_user.favourites
    @average_ratings = @favourite_recipes.map { |favourite| [favourite.recipe.id, favourite.recipe.ratings.average(:value)] }.to_h
  end

  def create
    if current_user.favourites.exists?(recipe_id: params[:recipe])
      current_user.favourites.find_by(recipe_id: params[:recipe]).destroy
    else
      favourite = Favourite.new(user_id: current_user.id, recipe_id: params[:recipe])
      favourite.save
    end
  end

  def destroy
    favourite = current_user.favourites.find_by(id: params[:id])
    favourite.destroy
    redirect_to favourite_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def about
  end

  def contact
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  def index
    @rated_recipes = current_user.ratings
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @rating = Rating.new(value: params[:value], recipe_id: @recipe.id, user_id: current_user.id)

      if @rating.save
        redirect_to recipe_path(@recipe)
      else
        redirect_to recipe_path(@recipe)
      end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
    @trending_categories = Category.all.shuffle.first(4)
    @explore_more = (Category.all - @trending_categories).shuffle.first(5)
    @explore_more_buttons = (Category.all - @trending_categories - @explore_more).shuffle.first(4)

    if params[:query].present?
      @recipes = Recipe.search_by_recipe(params[:query])
    else
      @recipes = Recipe.all.shuffle.first(3)
    end

    @no_results = @recipes.empty?
  end

  def show
    @recipe = Recipe.find(params[:id])
    @current_user_ratings_count = current_user.ratings.where(recipe_id: @recipe.id).count
    @total_ratings_count = @recipe.ratings.count
    @average_rating = @recipe.ratings.average(:value)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HeavenlyRecipes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville:ital,wght@0,400;0,700;1,400&family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    <%= javascript_include_tag 'favourite' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <div data-controller="flash-message">
      <% if flash[:notice].present? %>
        <p class="notice" data-flash-message-target="message"><%= flash[:notice] %></p>
      <% end %>
      <% if flash[:alert].present? %>
        <p class="alert" data-flash-message-target="message"><%= flash[:alert] %></p>
      <% end %>
    </div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About page</h1>

app/views/pages/contact.html.erb
<h1>Contact Page</h1>

app/views/pages/search.html.erb
<h2>Search Results for "<%= @query.capitalize %>"</h2>

<% if @search_recipe_data.present? %>
  <% @search_recipe_data.each do |meal| %>
    <div>
      <%= link_to recipe_path(meal[:id]) do %>
        <%= image_tag meal[:photo], alt: meal[:name] %>
      <% end %>
      <%= link_to(favourites_path) do %>
        <i class="fas fa-heart"></i>
      <% end %>
      <h2><%= meal[:name] %></h2>
    </div>
  <% end %>
<% else %>
  <p>No results found.</p>
<% end %>

app/views/shared/_heart_icon.html.erb
<% if current_user.favourites.exists?(recipe_id: recipe.id) %>
  <%= link_to favourites_create_path(recipe: recipe.id), data: { turbo_method: :post }, remote: true do %>
    <i class="fas fa-heart clicked"></i>
  <% end %>
<% else %>
  <%= link_to favourites_create_path(recipe: recipe.id), data: { turbo_method: :post }, remote: true do %>
    <i class="fas fa-heart"></i>
  <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-container">
  <h1 id="logoname">Heavenly Recipes</h1>

  <div class="navbar-links">
    <%= link_to 'Home', root_path, class: "nav-link" %>
    <%= link_to 'About', about_path, class: "nav-link" %>
    <%= link_to 'Contact', contact_path, class: "nav-link" %>
  </div>

  <%= form_with(url: recipes_path, method: :get, class: "search-form-control form-group") do |form| %>
    <%= form.text_field :query, class: "form-control string required", id: "search_query", placeholder: "Search Recipe" %>
    <%= form.button type: "submit", class: "btn btn-flat" do %>
      <i class="fas fa-search"></i>
    <% end %>
  <% end %>

  <div class="navbar-links">
    <% if user_signed_in? %>
      <ul>
        <li>
          <a href="<%= favourites_path %>">
            <i class="fas fa-heart"></i>
          </a>
        </li>
        <li>
          <a href="<%= account_path %>">
            <i class="fas fa-user"></i>
          </a>
          <ul>
            <li>
              <%= link_to "Log-out", destroy_user_session_path, class: "logout-link", data: { turbo_method: :delete } %>
            </li>
          </ul>
        </li>
      </ul>
    <% else %>
      <ul>
        <li>
          <a href="<%= account_path %>">
            <i class="fas fa-user"></i>
          </a>
          <ul>
            <li>
              <%= link_to "Log-in", new_user_session_path %>
              <%= link_to "Sign Up", new_user_registration_path %>
            </li>
          </ul>
        </li>
      </ul>
    <% end %>
  </div>
</div>