config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "recipes#index"
  get "/recipes", to: "recipes#index"
  get "/about", to: "pages#about"
  get "/contact", to: "pages#contact"
  get "/recipes/:id", to: "recipes#show", as: "recipe"
  get "/favourites", to: "favourites#index"
  get "/ratings", to: "ratings#index"
  get "/account", to: "accounts#show"
  get "/category/:title", to: "categories#show", as: "category_show"
  get "/favourites/create", to: "favourites#create"

  post "/favourites/create", to: "favourites#create"
  post "/ratings/create", to: "ratings#create"
  delete '/favourites/:id', to: 'favourites#destroy', as: :favourite

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :recipe
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :user
  belongs_to :recipe

  validates_uniqueness_of :recipe_id, scope: :user_id
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :recipe
  belongs_to :user

  validates :value, presence: true, inclusion: { in: 1..5 }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :category
  has_many :favourites
  has_many :ratings

  include PgSearch::Model
  pg_search_scope :search_by_recipe,
                  against: [ :title ],
                  associated_against: {
                  category:[ :title ]
                  },
                  using: {
                    tsearch: { prefix: true }
                  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :favourites
  has_many :ratings
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def show
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find_by(title: params[:title].capitalize)
    @recipes = Recipe.where(category_id: @category.id)
  end
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  before_action :authenticate_user!

  def index
    @favourite_recipes = current_user.favourites
    @average_ratings = @favourite_recipes.map { |favourite| [favourite.recipe.id, favourite.recipe.ratings.average(:value)] }.to_h
  end

  def create
    if current_user.favourites.exists?(recipe_id: params[:recipe])
      current_user.favourites.find_by(recipe_id: params[:recipe]).destroy
    else
      favourite = Favourite.new(user_id: current_user.id, recipe_id: params[:recipe])
      favourite.save
    end
  end

  def destroy
    favourite = current_user.favourites.find_by(id: params[:id])
    favourite.destroy
    redirect_to favourite_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def about
  end

  def contact
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  def index
    @rated_recipes = current_user.ratings
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @rating = Rating.new(value: params[:value], recipe_id: @recipe.id, user_id: current_user.id)

      if @rating.save
        redirect_to recipe_path(@recipe)
      else
        redirect_to recipe_path(@recipe)
      end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
    @trending_categories = Category.all.shuffle.first(4)
    @explore_more = (Category.all - @trending_categories).shuffle.first(5)
    @explore_more_buttons = (Category.all - @trending_categories - @explore_more).shuffle.first(4)

    if params[:query].present?
      @recipes = Recipe.search_by_recipe(params[:query])
    else
      @recipes = Recipe.all.shuffle.first(3)
    end

    @no_results = @recipes.empty?
  end

  def show
    @recipe = Recipe.find(params[:id])
    @current_user_ratings_count = current_user.ratings.where(recipe_id: @recipe.id).count
    @total_ratings_count = @recipe.ratings.count
    @average_rating = @recipe.ratings.average(:value)
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/categories/show.html.erb
<div class="categories-container">
  <div class="category-search-results-number">
    <span class="border"><%= @category.title.capitalize %> Recipes</span>
  </div>
  <div class="latest-categories">
    <% @recipes.each do |recipe| %>
      <div class="small-category-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= recipe.photo_url %>');">
        <div class="icons">
          <%= link_to favourites_create_path(recipe: recipe.id), data: {turbo_method: :post} do %>
            <i class="fas fa-heart"></i>
          <% end %>
        </div>
        <%= link_to recipe_path(recipe[:id]) do %>
          <div class="text">
            <h2><%= recipe.title %> <span class="star-button gold-star"></span></h2>
          </div>
          <div class="rating-info">
            <% if recipe.ratings.average(:value) == nil %>
              <span> (N/A) </span>
            <% else %>
              <span> (<%= recipe.ratings.average(:value) %>) </span>
            <% end %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/favourites/index.html.erb
<h1>Your Favourite Recipes</h1>

<% @favourite_recipes.each do |favourite| %>
  <div class="favourite-recipes">
    <div class="icons">
      <%= link_to favourite_path(favourite), method: :delete, data: { turbo_method: :delete } do %>
        <i class="fas fa-heart"></i>
      <% end %>
    </div>
    <div class="favourite-recipe-title">
      <h1><%= favourite.recipe.title %></h1>
    </div>
    <div class="favourite-recipe-photo">
      <%= link_to favourite.recipe do %>
        <img src="<%= favourite.recipe.photo_url %>" alt="<%= favourite.recipe.title %>">
      <% end %>
    </div>
    <div class="favourite-user-rating">
      <% if @average_ratings[favourite.recipe.id].present? %>
        <p>Your Rating: <%= "⭐️" * ((@average_ratings[favourite.recipe.id] * 2).round / 2.0) %></p>
      <% else %>
        <span>You haven't rated this recipe yet.</span>
      <% end %>
    </div>
  </div>
<% end %>

app/views/ratings/index.html.erb
<h1>Your Rated Recipes</h1>

<% @rated_recipes.each do |rating| %>
  <h1><%= rating.recipe.title %></h1>
<% end %>

app/views/recipes/index.html.erb
<div class="container">
  <% if params[:query].present? && !@no_results && @recipes.count > 1 %>
    <div class="index-search-results-number">
      <span class="border"><%= @recipes.count %> recipes for "<%= params[:query] %>"</span>
    </div>
  <% elsif params[:query].present? && !@no_results && @recipes.count == 1 %>
    <div class="index-search-results-number">
      <span class="border"><%= @recipes.count %> recipe for "<%= params[:query] %>"</span>
    </div>
  <% end %>
  <div class="latest-recipes">
    <% if @no_results %>
      <span>No Recipes Found</span>
    <% elsif params[:query].present? %>
      <div class="index-search-results">
        <% @recipes.each do |recipe| %>
          <div class="small-recipe-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= recipe.photo_url %>');">
            <div class="icons">
              <%= render partial: 'shared/heart_icon', locals: { recipe: recipe } %>
            </div>
            <%= link_to recipe_path(recipe[:id]) do %>
              <div class="text">
                <h2><%= recipe.title %> <span class="star-button gold-star"></span></h2>
              </div>
              <div class="rating-info">
                <% if recipe.ratings.average(:value) == nil %>
                  <span> (N/A) </span>
                <% else %>
                  <span> (<%= recipe.ratings.average(:value) %>) </span>
                <% end %>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    <% else %>
      <div class="large-recipe-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= @recipes[0].photo_url %>');">
        <div class="icons">
          <%= link_to favourites_create_path(recipe: @recipes[0].id), data: {turbo_method: :post} do %>
            <i class="fas fa-heart"></i>
          <% end %>
        </div>
        <%= link_to recipe_path(@recipes[0][:id]) do %>
          <div class="text">
            <h2><%= @recipes[0].title %></h2>
          </div>
        <% end %>
      </div>
      <div class="small-index-recipe-cards">
        <% @recipes[1..2].each do |recipe| %>
          <div class="small-index-recipe-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= recipe.photo_url %>');">
            <div class="icons">
              <%= link_to favourites_create_path(recipe: recipe.id), data: {turbo_method: :post} do %>
                <i class="fas fa-heart"></i>
              <% end %>
            </div>
            <%= link_to recipe_path(recipe[:id]) do %>
              <div class="text">
                <h2><%= recipe.title %></h2>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
  <% unless params[:query].present? %>
    <div class="trending-categories">
      <div class="trending-category-header">
        <div class="trending-category-heading">
          <h2 class="border">Trending Categories</h2>
        </div>
        <div class="trending-category-buttons">
          <% @explore_more_buttons.each do |category| %>
            <button><%= category.title %></button>
          <% end %>
        </div>
      </div>
      <div class="trending-category-images">
        <% @trending_categories.each do |category| %>
          <div class="trending-image" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= category.photo_url %>');">
            <%= link_to category_show_path(title: category.title.downcase) do %>
              <div class="text">
                <h2><%= category.title %></h2>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="explore-more">
      <div class="explore-more-header">
        <div class="explore-more-heading">
          <h2 class="border">Explore More</h2>
        </div>
      </div>
      <div class="explore-more-panes">
        <div class="explore-left-pane">
          <% @explore_more[0..1].each do |category| %>
            <div class="left-pane-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= category.photo_url %>');">
              <%= link_to category_show_path(title: category.title.downcase) do %>
                <div class="text">
                  <h2><%= category.title %></h2>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
        <% @explore_more[2..2].each do |category| %>
          <div class="explore-centre-pane" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= category.photo_url %>');">
            <%= link_to category_show_path(title: category.title.downcase) do %>
              <div class="text">
                <h2><%= category.title %></h2>
              </div>
            <% end %>
          </div>
        <% end %>
        <div class="explore-right-pane">
          <% @explore_more[3..4].each do |category| %>
            <div class="right-pane-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= category.photo_url %>');">
              <%= link_to category_show_path(title: category.title.downcase) do %>
                <div class="text">
                  <h2><%= category.title %></h2>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/recipes/show.html.erb
<div class="recipe-show-container">
  <div class="recipe-overall-details">
    <div class="recipe-photo-title">
      <div class="recipe-show-image" style="background-image: url('<%= @recipe.photo_url %>');">
        <div class="recipe-favourite-rating">
          <%= link_to favourites_create_path(recipe: @recipe.id), data: {turbo_method: :post} do %>
            <i class="fas fa-heart"></i>
          <% end %>
        </div>
      </div>
    </div>
    <div class="recipe-guide">
      <div class="recipe-title">
        <h1><%= @recipe.title %></h1>
      </div>
      <div class="recipe-rating">
        <% unless @current_user_ratings_count > 0 %>
          <%= form_tag({ controller: "ratings", action: "create", recipe_id: @recipe.id }, method: :post) do %>
            <div class="star-buttons-container">
              <% (1..5).each do |value| %>
                <%= button_tag type: "submit", class: "star-button", name: "value", value: 6 - value do %>
                <% end %>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
      <div class="recipe-rating-info">
        <% if @average_rating == nil %>
          <span class="recipe-star-button recipe-gold-star"></span>
          <span> No ratings yet </span>
        <% else %>
          <span class="recipe-star-button recipe-gold-star"></span>
          <span> (<%= @average_rating %>) (<%= @total_ratings_count %> <%= @total_ratings_count == 1 ? 'rating' : 'ratings' %>) </span>
        <% end %>
      </div>
      <div class="recipe-ingredients-measures">
        <h2><b>Ingredients :</b></h2>
        <ul>
          <% @recipe.ingredients.each_with_index do |ingredient, index| %>
            <% capitalized_ingredient = ingredient.capitalize %>
            <% capitalized_measure = @recipe.measures[index].capitalize %>
            <% if capitalized_measure.present? %>
              <li><%= "#{capitalized_ingredient} -> #{capitalized_measure}" %></li>
            <% else %>
              <li><%= "#{capitalized_ingredient}" %></li>
            <% end %>
          <% end %>
        </ul>
      </div>
      <div class="recipe-instructions">
        <h2><b>Instructions :</b></h2>
        <p>
          <%= @recipe.instructions %>
        </p>
      </div>
    </div>
  </div>
</div>